name: Scheduled Build

on:
    workflow_dispatch:
    push:
        branches: ['main']
    schedule:
        - cron: '0 0 * * 0'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build SQLite file
              run: python3 ./build.py 2> build.log

            - name: Create compressed files for distribution
              run: |
                  gzip -c -9 pokeapi.sqlite > pokeapi.sqlite.gz
                  xz   -c -9 pokeapi.sqlite > pokeapi.sqlite.xz

            - name: Commit to dist branch
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git checkout --orphan dist
                  git rm --cached -r .

                  git config user.name "$GITHUB_ACTOR"
                  git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

                  git add pokeapi.sqlite.gz pokeapi.sqlite.xz build.log
                  git commit -m "Build for $GITHUB_SHA"

                  git push origin dist --force
